const DEV_DATABASE_DRAFT_KEY = "su-majestad-dev-database-draft-v1";
const DEV_SCHEMA_VERSION = 1;
const RESOURCE_KEYS = new Set(Object.keys(resourceMeta || {}));
const developerState = {
  activeTab: "events", eventTab: "general", selected: { events: null, families: null, actors: null },
  events: [], families: [], actors: [], filters: { search: "", family: "", kind: "", special: "" },
  optionOpen: 0, jsonError: "", message: "", validation: { errors: [], warnings: [] }, tagSearch: ""
};

function cloneDeveloperValue(value) { return JSON.parse(JSON.stringify(value || [])); }
function bootDeveloperEditor() {
  developerState.events = cloneDeveloperValue(window.eventsDatabase || events || []);
  developerState.families = cloneDeveloperValue(typeof families !== "undefined" ? families : []);
  developerState.actors = cloneDeveloperValue(typeof actors !== "undefined" ? actors : []);
  developerState.selected.events = developerState.events[0]?.id || null;
  developerState.selected.families = developerState.families[0]?.id || null;
  developerState.selected.actors = developerState.actors[0]?.id || null;
  bindDeveloperControls();
  developerState.validation = validateDeveloperDatabase();
}
function bindDeveloperControls() {
  const byId = (id) => document.getElementById(id);
  byId("developerModeButton")?.addEventListener("click", () => setScreen("developer"));
  byId("developerBackButton")?.addEventListener("click", () => setScreen("menu"));
  byId("developerExportButton")?.addEventListener("click", exportDeveloperDatabase);
  byId("developerDraftButton")?.addEventListener("click", () => { localStorage.setItem(DEV_DATABASE_DRAFT_KEY, JSON.stringify(buildDeveloperDatabase(), null, 2)); renderDeveloperEditor("Borrador de base de datos guardado."); });
  byId("developerLoadDraftButton")?.addEventListener("click", loadDeveloperDraft);
  byId("developerValidateButton")?.addEventListener("click", () => { developerState.activeTab = "validation"; renderDeveloperEditor("Validación actualizada."); });
  byId("developerImportInput")?.addEventListener("change", importDeveloperDatabase);
}
function renderDeveloperEditor(message = "") {
  if (currentScreen !== "developer") return;
  developerState.message = message;
  developerState.validation = validateDeveloperDatabase();
  const root = document.getElementById("developerRoot");
  if (!root) return;
  root.innerHTML = `${renderDeveloperTabs()}${message ? `<p class="validation-info">${escapeHtml(message)}</p>` : ""}${renderDeveloperActiveTab()}`;
  bindRenderedDeveloperControls(root);
}
function renderDeveloperTabs() {
  const tabs = [["events","Eventos"],["families","Familias"],["actors","Actores"],["gameData","Datos del juego"],["validation","Validación"]];
  return `<nav class="developer-tabs" aria-label="Base de datos">${tabs.map(([id,label]) => `<button class="${developerState.activeTab === id ? "active" : ""}" type="button" data-dev-tab="${id}">${label}</button>`).join("")}</nav>`;
}
function renderDeveloperActiveTab() {
  if (developerState.activeTab === "events") return renderEventsDatabase();
  if (developerState.activeTab === "families") return renderSimpleDatabase("families");
  if (developerState.activeTab === "actors") return renderSimpleDatabase("actors");
  if (developerState.activeTab === "gameData") return renderGameDataTab();
  return renderValidationTab();
}
function bindRenderedDeveloperControls(root) {
  root.querySelectorAll("[data-dev-tab]").forEach((button) => button.addEventListener("click", () => { developerState.activeTab = button.dataset.devTab; renderDeveloperEditor(); }));
  root.querySelectorAll("[data-select-record]").forEach((button) => button.addEventListener("click", () => { developerState.selected[button.dataset.recordType] = button.dataset.selectRecord; renderDeveloperEditor(); }));
  root.querySelectorAll("[data-filter]").forEach((field) => field.addEventListener("input", () => { developerState.filters[field.dataset.filter] = field.value; renderDeveloperEditor(); }));
  root.querySelectorAll("[data-filter-change]").forEach((field) => field.addEventListener("change", () => { developerState.filters[field.dataset.filterChange] = field.value; renderDeveloperEditor(); }));
  root.querySelectorAll("[data-event-tab]").forEach((button) => button.addEventListener("click", () => { developerState.eventTab = button.dataset.eventTab; renderDeveloperEditor(); }));
  root.querySelectorAll("[data-field]").forEach((field) => field.addEventListener("input", updateSelectedField));
  root.querySelectorAll("[data-change-field]").forEach((field) => field.addEventListener("change", updateSelectedField));
  root.querySelectorAll("[data-chip-toggle]").forEach((field) => field.addEventListener("change", toggleChipValue));
  root.querySelectorAll("[data-action]").forEach((button) => button.addEventListener("click", handleDeveloperAction));
}
function buildDeveloperDatabase() { return { schemaVersion: DEV_SCHEMA_VERSION, events: developerState.events, families: developerState.families, actors: developerState.actors }; }
function optionList(option) { return Array.isArray(option) ? option : (option ? [option] : []); }
function familyOptions(value = "") { const extra = value && !developerState.families.some((f) => f.id === value) ? `<option value="${escapeHtml(value)}" selected>⚠ ${escapeHtml(value)}</option>` : ""; return `<option value="">Sin familia</option>${extra}${developerState.families.map((f) => `<option value="${escapeHtml(f.id)}" ${value === f.id ? "selected" : ""}>${escapeHtml(f.name || f.id)}</option>`).join("")}`; }
function eventOptions(value = "") { const extra = value && !developerState.events.some((e) => e.id === value) ? `<option value="${escapeHtml(value)}" selected>⚠ ${escapeHtml(value)}</option>` : ""; return `<option value="">Sin evento</option>${extra}${developerState.events.map((e) => `<option value="${escapeHtml(e.id)}" ${value === e.id ? "selected" : ""}>${escapeHtml(e.title || e.id)} (${escapeHtml(e.id)})</option>`).join("")}`; }
function actorOptions(value = "") { return `<option value="">Sin actor</option>${developerState.actors.map((a) => `<option value="${escapeHtml(a.id)}" ${value === a.id ? "selected" : ""}>${escapeHtml(a.name || a.id)} · ${escapeHtml(a.role || "sin rol")} · ${escapeHtml(a.family || "sin familia")}</option>`).join("")}`; }
function resourceOptions(value = "") { return [...RESOURCE_KEYS].map((key) => `<option value="${key}" ${value === key ? "selected" : ""}>${resourceMeta[key]?.[1] || ""} ${resourceMeta[key]?.[0] || key}</option>`).join(""); }
function allTags() { const tags = []; const add = (xs) => Array.isArray(xs) && tags.push(...xs); developerState.events.forEach((e) => { add(e.requiresTags); add(e.forbiddenTags); (e.options || []).forEach((o) => add(o.addTags)); }); developerState.families.forEach((f) => add(f.commonTags)); developerState.actors.forEach((a) => add(a.tags)); return [...new Set(tags)].sort(); }
function renderChipSelector(type, field, values = []) { const options = allTags().map((id) => ({ id, name: id })); return `<div class="dev-chip-box">${options.map((item) => `<label class="dev-chip"><input type="checkbox" data-chip-toggle="${field}" value="${escapeHtml(item.id)}" ${values.includes(item.id) ? "checked" : ""}>${escapeHtml(item.name || item.id)}</label>`).join("")}</div><div class="developer-inline"><input data-field="${field}" value="${escapeHtml(values.join(", "))}" placeholder="Añadir por CSV/autocompletar"><small>Los valores nuevos se conservan para compatibilidad.</small></div>`; }
function filteredDeveloperEvents() { const f = developerState.filters, q = f.search.trim().toLowerCase(); return developerState.events.filter((e) => { if (q && !JSON.stringify(e).toLowerCase().includes(q)) return false; if (f.family && e.family !== f.family) return false; if (f.kind && (e.kind || "normal") !== f.kind) return false; if (f.special === "normal" && (e.kind || "normal") === "consequence") return false; if (f.special === "consequence" && (e.kind || "normal") !== "consequence") return false; if (f.special === "defer" && !eventHasDefer(e)) return false; if (f.special === "no-defer" && eventHasDefer(e)) return false; if (f.special === "issue" && !eventHasIssue(e)) return false; if (f.special === "no-issue" && eventHasIssue(e)) return false; if (f.special === "errors" && !developerState.validation.errors.some((p) => p.recordId === e.id)) return false; return true; }); }
function renderEventsDatabase() { const items = filteredDeveloperEvents(), selected = selectedEvent(); return `<section class="developer-layout"><aside class="developer-list-panel"><div class="developer-toolbar compact"><input data-filter="search" value="${escapeHtml(developerState.filters.search)}" placeholder="Buscar ID, título o texto"><select data-filter-change="family">${familyOptions(developerState.filters.family)}</select><select data-filter-change="kind"><option value="">Todos los tipos</option><option value="normal" ${developerState.filters.kind === "normal" ? "selected" : ""}>normal</option><option value="consequence" ${developerState.filters.kind === "consequence" ? "selected" : ""}>consequence</option></select><select data-filter-change="special"><option value="">Todos</option><option value="normal">Normales</option><option value="consequence">Consecuencias</option><option value="defer">Con defer</option><option value="no-defer">Sin defer</option><option value="issue">Con issue</option><option value="no-issue">Sin issue</option><option value="errors">Con errores</option></select></div><div class="developer-actions compact"><button class="primary-button" data-action="new-event" type="button">Crear</button><button class="secondary-button" data-action="duplicate-event" type="button">Duplicar</button><button class="danger-button" data-action="delete-event" type="button">Borrar</button></div><p class="developer-count">${items.length} / ${developerState.events.length} eventos</p><div class="developer-scroll-list">${items.map(renderEventListItem).join("")}</div></aside><section class="developer-editor">${selected ? renderEventEditor(selected) : "<p>No hay eventos.</p>"}</section></section>`; }
function renderEventListItem(e) { const hasError = developerState.validation.errors.some((p) => p.recordId === e.id), hasWarning = developerState.validation.warnings.some((p) => p.recordId === e.id); return `<button class="developer-list-item ${e.id === developerState.selected.events ? "selected" : ""}" data-record-type="events" data-select-record="${escapeHtml(e.id)}" type="button"><strong>${hasError ? "⛔ " : hasWarning ? "⚠️ " : ""}${escapeHtml(e.id || "sin-id")}</strong><span>${escapeHtml(e.title || "Sin título")}</span><small>${escapeHtml(e.family || "sin familia")} · ${escapeHtml(e.kind || "normal")}</small></button>`; }
function renderEventEditor(e) { const tabs = ["general","options","conditions","consequences","json"], labels = { general:"General", options:"Opciones", conditions:"Condiciones", consequences:"Consecuencias", json:"JSON avanzado" }; return `<h3>${escapeHtml(e.title || e.id)}</h3><nav class="developer-subtabs">${tabs.map((t) => `<button class="${developerState.eventTab === t ? "active" : ""}" data-event-tab="${t}" type="button">${labels[t]}</button>`).join("")}</nav>${renderEventTab(e)}`; }
function renderEventTab(e) { if (developerState.eventTab === "options") return renderEventOptions(e); if (developerState.eventTab === "conditions") return `<div class="developer-form-grid">${tagSelector("requiresTags","Requires tags",e.requiresTags)}${tagSelector("forbiddenTags","Forbidden tags",e.forbiddenTags)}${textInput("issue","Issue",e.issue || "")}${textareaInput("resourceConditions","Resource conditions JSON", JSON.stringify(e.resourceConditions || {}, null, 2), true)}${textareaInput("resourceWeights","Resource weights JSON", JSON.stringify(e.resourceWeights || [], null, 2), true)}</div>`; if (developerState.eventTab === "consequences") return renderConsequences(e); if (developerState.eventTab === "json") return `<div class="developer-json open"><textarea id="developerAdvancedJson" spellcheck="false">${escapeHtml(JSON.stringify(e, null, 2))}</textarea><div class="developer-actions compact"><button class="primary-button" data-action="apply-event-json" type="button">Aplicar JSON</button><button class="secondary-button" data-action="format-event-json" type="button">Formatear JSON</button></div>${developerState.jsonError ? `<p class="validation-error">${escapeHtml(developerState.jsonError)}</p>` : ""}</div>`; return `<div class="developer-form-grid">${textInput("id","ID",e.id)}${textInput("title","Título",e.title)}${textareaInput("text","Texto",e.text)}<label>Familia<select data-change-field="family">${familyOptions(e.family || "")}</select></label><label>Kind<select data-change-field="kind"><option value="">normal</option><option value="normal" ${(e.kind || "normal") === "normal" ? "selected" : ""}>normal</option><option value="consequence" ${e.kind === "consequence" ? "selected" : ""}>consequence</option></select></label>${numberInput("weight","Weight",e.weight)}${numberInput("minDay","MinDay",e.minDay)}${numberInput("maxDay","MaxDay",e.maxDay)}</div>`; }
function renderEventOptions(e) { return `<div class="developer-actions compact"><button class="primary-button" data-action="add-option" type="button">Añadir opción</button></div><div class="developer-options">${(e.options || []).map((o,i) => renderOptionCard(o,i)).join("")}</div>`; }
function renderOptionCard(o, i) { const open = developerState.optionOpen === i; return `<article class="developer-option ${open ? "open" : ""}"><div class="developer-option-summary"><button type="button" data-action="open-option" data-index="${i}"><strong>${i + 1}. ${escapeHtml(o.label || "Sin label")}</strong><small>${summarizeOption(o)}</small></button><div><button data-action="duplicate-option" data-index="${i}" type="button">Duplicar</button><button data-action="move-option-up" data-index="${i}" type="button">↑</button><button data-action="move-option-down" data-index="${i}" type="button">↓</button><button class="danger-button" data-action="delete-option" data-index="${i}" type="button">Borrar</button></div></div>${open ? renderOpenOption(o,i) : ""}</article>`; }
function renderOpenOption(o,i) { return `<div class="developer-form-grid"><label>Label<input data-field="option.label" data-index="${i}" value="${escapeHtml(o.label || "")}"></label>${textareaInput(`option.resultText:${i}`,"Texto de resultado",o.resultText || "")}<details open><summary>Efectos inmediatos</summary>${renderEffectsEditor(o.immediate || {}, `option.immediate:${i}`)}</details><details><summary>Outcomes aleatorios</summary>${textareaInput(`option.outcomes:${i}`,"Outcomes JSON", JSON.stringify(o.outcomes || [], null, 2), true)}</details><details><summary>Tags</summary>${tagSelector(`option.addTags:${i}`,"Tags añadidos",o.addTags)}</details><details><summary>Actores</summary>${renderCharactersEditor(o.characters || [], i)}</details><details><summary>Issues</summary>${textareaInput(`option.issues:${i}`,"Issues JSON", JSON.stringify(o.issues || [], null, 2), true)}</details><details><summary>Consecuencias diferidas</summary>${renderDeferEditor(o.defer, i)}</details></div>`; }
function renderEffectsEditor(map, field) { const rows = Object.entries(map); return `<div class="dev-effects">${rows.map(([key,value],idx)=>`<div class="developer-inline"><select data-field="${field}.key" data-index="${idx}">${resourceOptions(key)}</select><input type="number" data-field="${field}.value" data-index="${idx}" value="${value}"><button data-action="delete-effect" data-field="${field}" data-index="${idx}" type="button">Eliminar</button></div>`).join("") || `<p class="developer-empty">+ Añadir efecto</p>`}<button data-action="add-effect" data-field="${field}" type="button">Añadir efecto</button></div>`; }
function renderCharactersEditor(chars, optionIndex) { return `${chars.map((c,i)=>`<div class="developer-inline"><select data-field="option.characters:${optionIndex}.id" data-index="${i}">${actorOptions(c.id)}</select><input data-field="option.characters:${optionIndex}.note" data-index="${i}" value="${escapeHtml(c.note || "")}" placeholder="nota"><button data-action="delete-character" data-option="${optionIndex}" data-index="${i}" type="button">Eliminar</button></div>`).join("") || `<p class="developer-empty">+ Añadir actor</p>`}<button data-action="add-character" data-index="${optionIndex}" type="button">Añadir actor</button>`; }
function renderDeferEditor(defer, optionIndex) { const list = optionList(defer); return `${list.map((d,i)=>`<div class="developer-reference"><label>Evento<select data-field="option.defer:${optionIndex}.eventId" data-index="${i}">${eventOptions(d.eventId)}</select></label><label>Delay<input type="number" data-field="option.defer:${optionIndex}.delay" data-index="${i}" value="${d.delay || 1}"></label><button data-action="open-referenced-event" data-event-id="${escapeHtml(d.eventId || "")}" type="button">Abrir evento</button><button data-action="delete-defer" data-option="${optionIndex}" data-index="${i}" type="button">Eliminar</button></div>${(d.branches || []).map((b,bi)=>`<div class="developer-reference branch"><label>Rama ${bi + 1}<select data-field="option.defer:${optionIndex}.branchEvent" data-index="${i}" data-branch="${bi}">${eventOptions(b.eventId)}</select></label><input type="number" step="0.01" data-field="option.defer:${optionIndex}.branchProbability" data-index="${i}" data-branch="${bi}" value="${b.probability ?? ""}"><button data-action="open-referenced-event" data-event-id="${escapeHtml(b.eventId || "")}" type="button">Abrir evento</button></div>`).join("")}`).join("") || `<p class="developer-empty">+ Añadir consecuencia diferida</p>`}<button data-action="add-defer" data-index="${optionIndex}" type="button">Añadir consecuencia diferida</button>`; }
function renderConsequences(e) { const rows = []; (e.options || []).forEach((o, oi) => { optionList(o.defer).forEach((d) => { if (d.eventId) rows.push({ label:`Después de ${d.delay || 1} días`, id:d.eventId }); (d.branches || []).forEach((b) => rows.push({ label:`${Math.round((b.probability || 0)*100)} %`, id:b.eventId })); }); (o.issues || []).forEach((iss) => rows.push({ label:`Issue ${iss.action || "modifica"}`, id: iss.id || iss.type || "" })); (o.characters || []).forEach((c) => rows.push({ label:"Actor recordado", id: c.id || "" })); }); return `<div class="developer-summary-list">${rows.map((r)=>{ const target = developerState.events.find((ev)=>ev.id===r.id); return `<article class="developer-reference ${target ? "" : "broken"}"><strong>${escapeHtml(r.label)} → ${escapeHtml(target?.title || r.id || "referencia sin id")}</strong><small>${escapeHtml(r.id || "")}</small>${target ? `<button data-action="open-referenced-event" data-event-id="${escapeHtml(r.id)}" type="button">Abrir evento</button>` : `<span>Referencia rota o no navegable</span>`}</article>`; }).join("") || `<p>No hay consecuencias salientes.</p>`}</div>`; }
function renderSimpleDatabase(type) { const list = developerState[type], selected = list.find((x)=>x.id===developerState.selected[type]) || list[0]; return `<section class="developer-layout"><aside class="developer-list-panel"><div class="developer-actions compact"><button class="primary-button" data-action="new-${type}" type="button">Crear</button><button class="secondary-button" data-action="duplicate-${type}" type="button">Duplicar</button><button class="danger-button" data-action="delete-${type}" type="button">Borrar</button></div><p class="developer-count">${list.length} registros</p><div class="developer-scroll-list">${list.map((item)=>`<button class="developer-list-item ${item.id===developerState.selected[type]?"selected":""}" data-record-type="${type}" data-select-record="${escapeHtml(item.id)}" type="button"><strong>${escapeHtml(item.name || item.id)}</strong><span>${escapeHtml(item.id)}</span><small>${recordUsageLabel(type,item.id)}</small></button>`).join("")}</div></aside><section class="developer-editor">${selected ? renderRecordEditor(type, selected) : "<p>Sin registros.</p>"}</section></section>`; }
function renderRecordEditor(type, item) { if (type === "families") return `<h3>${escapeHtml(item.name || item.id)}</h3><div class="developer-form-grid">${textInput("id","ID",item.id,type)}${textInput("name","Nombre",item.name,type)}${textareaInput("description","Descripción",item.description || "",false,type)}${tagSelector("commonTags","Tags comunes",item.commonTags,"","tags",type)}${tagSelector("compatibleIssueTypes","Tipos de issue compatibles",item.compatibleIssueTypes,"","tags",type)}</div>`; return `<h3>${escapeHtml(item.name || item.id)}</h3><p>${eventsUsingActor(item.id).length} eventos usan este actor. <button data-action="filter-actor-events" data-actor-id="${escapeHtml(item.id)}" type="button">Ver eventos</button></p><div class="developer-form-grid">${textInput("id","ID",item.id,type)}${textInput("name","Nombre",item.name,type)}${textInput("role","Rol",item.role || "",type)}<label>Familia<select data-change-field="family" data-record="${type}">${familyOptions(item.family || "")}</select></label>${tagSelector("tags","Tags",item.tags,"","tags",type)}${numberInput("trust","Trust inicial",item.trust,type)}${numberInput("tension","Tension inicial",item.tension,type)}${textareaInput("description","Descripción",item.description || "",false,type)}</div>`; }
function renderGameDataTab() { const tagCounts = tagIndex(); const issueTypes = issueTypeIndex(); return `<section class="developer-data-grid"><article><h3>Recursos</h3>${[...RESOURCE_KEYS].map((key)=>`<p><strong>${resourceMeta[key]?.[1] || ""} ${resourceMeta[key]?.[0] || key}</strong> <code>${key}</code>${key === "threat" ? " · inverso" : " · normal"}</p>`).join("")}</article><article><h3>Tipos de evento</h3><p><code>normal</code></p><p><code>consequence</code></p></article><article><h3>Tags</h3>${tagCounts.map((t)=>`<p><strong>${escapeHtml(t.tag)}</strong> · ${t.count} usos <small>${escapeHtml(t.where.slice(0,3).join(", "))}</small></p>`).join("")}</article><article><h3>Tipos de issue</h3>${issueTypes.map((i)=>`<p><strong>${escapeHtml(i.id)}</strong> · crea/modifica en ${i.events.length} eventos</p>`).join("") || "<p>Sin issues indexados.</p>"}</article></section>`; }
function renderValidationTab() { const groups = [["Errores", developerState.validation.errors, "validation-error"],["Avisos", developerState.validation.warnings, "validation-warning"]]; return `<section class="developer-validation big">${groups.map(([title,items,klass])=>`<h3>${title} (${items.length})</h3><div class="developer-summary-list">${items.map((p)=>`<article class="${klass}"><strong>${escapeHtml(p.message)}</strong><button data-action="go-problem" data-tab="${p.tab}" data-record-id="${escapeHtml(p.recordId || "")}" type="button">Ir al registro</button></article>`).join("") || "<p>Sin problemas.</p>"}</div>`).join("")}</section>`; }
function textInput(field,label,value="",record="events") { return `<label>${label}<input data-field="${field}" data-record="${record}" value="${escapeHtml(value ?? "")}"></label>`; }
function numberInput(field,label,value,record="events") { return `<label>${label}<input type="number" data-field="${field}" data-record="${record}" value="${Number.isFinite(value) ? value : ""}"></label>`; }
function textareaInput(field,label,value="",json=false,record="events") { return `<label class="wide">${label}<textarea data-field="${field}" data-record="${record}" ${json ? "data-json='true'" : ""}>${escapeHtml(value ?? "")}</textarea></label>`; }
function tagSelector(field,label,values=[],family="",type="tags",record="events") { return `<label class="wide">${label}${renderChipSelector(type, field, values || [], family)}</label>`; }
function selectedEvent() { return developerState.events.find((e)=>e.id===developerState.selected.events) || developerState.events[0]; }
function selectedRecord(type) { return type === "events" ? selectedEvent() : (developerState[type].find((x)=>x.id===developerState.selected[type]) || developerState[type][0]); }
function updateSelectedField(e) { const recordType = e.target.dataset.record || "events", field = e.target.dataset.field, item = selectedRecord(recordType); if (!item) return; setDeveloperField(item, field, e.target.value, e.target); if (field === "id") developerState.selected[recordType] = e.target.value; renderDeveloperEditor(); }
function setDeveloperField(item, field, value, target) { if (field.includes(":") || field.includes(".")) return setComplexField(item, field, value, target); if (["requiresTags","forbiddenTags","commonTags","compatibleIssueTypes","tags"].includes(field)) item[field] = csv(value); else if (["weight","minDay","maxDay","trust","tension"].includes(field)) value === "" ? delete item[field] : item[field] = Number(value); else if (target?.dataset.json) { try { item[field] = JSON.parse(value || (value.trim().startsWith("[") ? "[]" : "{}")); } catch { target.classList.add("invalid"); return; } } else value === "" ? delete item[field] : item[field] = value; }
function setComplexField(event, field, value, target) {
  if (field === "option.label") { const option = event.options?.[Number(target.dataset.index)]; if (option) option.label = value; return; }
  const [path, indexText] = field.split(":"), i = Number(indexText); const option = event.options?.[i]; if (!option) return;
  if (path === "option.immediate.key") { const entries = Object.entries(option.immediate || {}), old = entries[Number(target.dataset.index)]?.[0]; if (old) { const amount = option.immediate[old]; delete option.immediate[old]; option.immediate[value] = amount; } return; }
  if (path === "option.immediate.value") { const key = Object.keys(option.immediate || {})[Number(target.dataset.index)]; if (key) option.immediate[key] = Number(value); return; }
  if (path === "option.characters") { const chars = option.characters || []; const c = chars[Number(target.dataset.index)] || {}; if (field.endsWith(".id")) c.id = value; if (field.endsWith(".note")) c.note = value; chars[Number(target.dataset.index)] = c; option.characters = chars; return; }
  if (path === "option.defer") { const list = optionList(option.defer), d = list[Number(target.dataset.index)] || {}; if (field.endsWith(".eventId")) d.eventId = value; if (field.endsWith(".delay")) d.delay = Number(value); list[Number(target.dataset.index)] = d; option.defer = list; return; }
  const key = path.replace("option.", ""); if (["outcomes","issues"].includes(key)) { try { option[key] = JSON.parse(value || "[]"); } catch { target.classList.add("invalid"); } } else if (key === "resultText") option.resultText = value; else if (key === "addTags") option.addTags = csv(value); }
function toggleChipValue(e) { const item = selectedRecord(e.target.dataset.record || "events"), field = e.target.dataset.chipToggle; if (!item) return; const values = new Set(item[field] || []); e.target.checked ? values.add(e.target.value) : values.delete(e.target.value); item[field] = [...values]; renderDeveloperEditor(); }
function handleDeveloperAction(e) { const a = e.currentTarget.dataset.action; const event = selectedEvent(); if (a === "new-event") return createRecord("events", { id: uniqueId("nuevo_evento", developerState.events), title: "Nuevo evento", text: "Describe el asunto.", family: "", options: [{ label: "Aceptar", immediate: {}, resultText: "" }] }); if (a === "duplicate-event") return duplicateRecord("events"); if (a === "delete-event") return deleteRecord("events"); if (a === "add-option") { event.options = [...(event.options || []), { label:"Nueva opción", immediate:{}, addTags:[], characters:[], issues:[], outcomes:[], resultText:"" }]; developerState.optionOpen = event.options.length - 1; return renderDeveloperEditor(); } if (a === "open-option") { developerState.optionOpen = Number(e.currentTarget.dataset.index); return renderDeveloperEditor(); } if (a === "delete-option") { event.options.splice(Number(e.currentTarget.dataset.index),1); developerState.optionOpen = 0; return renderDeveloperEditor(); } if (a === "duplicate-option") { const i=Number(e.currentTarget.dataset.index); event.options.splice(i+1,0,cloneDeveloperValue(event.options[i])); developerState.optionOpen=i+1; return renderDeveloperEditor(); } if (a?.startsWith("move-option")) { const i=Number(e.currentTarget.dataset.index), d=a.endsWith("up")?-1:1, j=i+d; if (j>=0 && j<event.options.length) [event.options[i],event.options[j]]=[event.options[j],event.options[i]], developerState.optionOpen=j; return renderDeveloperEditor(); } if (a === "apply-event-json") return applyDeveloperAdvancedJson(); if (a === "format-event-json") return formatDeveloperAdvancedJson(); if (a === "open-referenced-event") return openDeveloperEvent(e.currentTarget.dataset.eventId); if (a === "go-problem") return goDeveloperProblem(e.currentTarget.dataset.tab, e.currentTarget.dataset.recordId); if (a?.startsWith("new-") || a?.startsWith("duplicate-") || a?.startsWith("delete-")) { const type = a.split("-").slice(1).join("-"); return a.startsWith("new") ? createTypedRecord(type) : a.startsWith("duplicate") ? duplicateRecord(type) : deleteRecord(type); } if (a === "add-effect") return addEffect(e.currentTarget.dataset.field); if (a === "delete-effect") return deleteEffect(e.currentTarget.dataset.field, Number(e.currentTarget.dataset.index)); if (a === "add-character") return addCharacter(Number(e.currentTarget.dataset.index)); if (a === "delete-character") return deleteCharacter(Number(e.currentTarget.dataset.option), Number(e.currentTarget.dataset.index)); if (a === "add-defer") return addDefer(Number(e.currentTarget.dataset.index)); if (a === "delete-defer") return deleteDefer(Number(e.currentTarget.dataset.option), Number(e.currentTarget.dataset.index)); }
function createTypedRecord(type) { const base = type === "families" ? { id: uniqueId("nueva_familia", developerState[type]), name:"Nueva familia", description:"", commonTags:[], compatibleIssueTypes:[] } : { id: uniqueId("nuevo_actor", developerState[type]), name:"Nuevo actor", role:"", family:"", tags:[], trust:50, tension:20, description:"" }; createRecord(type, base); }
function createRecord(type, record) { developerState[type].unshift(record); developerState.selected[type] = record.id; renderDeveloperEditor(); }
function duplicateRecord(type) { const item = selectedRecord(type); if (!item) return; const copy = cloneDeveloperValue(item); copy.id = uniqueId(`${item.id || "registro"}_copia`, developerState[type]); copy.name = `${copy.name || copy.title || "Registro"} (copia)`; developerState[type].splice(developerState[type].indexOf(item)+1,0,copy); developerState.selected[type]=copy.id; renderDeveloperEditor(); }
function deleteRecord(type) { const item = selectedRecord(type); if (!item) return; const refs = recordReferences(type, item.id); if (!confirm(`${refs}\n\n¿Borrar ${item.id}?`)) return; developerState[type].splice(developerState[type].indexOf(item),1); developerState.selected[type]=developerState[type][0]?.id || null; renderDeveloperEditor(); }
function recordReferences(type,id) { if (type === "families") return `${eventsUsingFamily(id).length} eventos y ${developerState.actors.filter(a=>a.family===id).length} actores usan esta familia.`; if (type === "actors") return `${eventsUsingActor(id).length} eventos usan este actor.`; return "Las referencias diferidas a este evento podrían romperse."; }
function recordUsageLabel(type,id) { if (type === "families") return `${eventsUsingFamily(id).length} eventos`; if (type === "actors") return `${developerState.actors.find(a=>a.id===id)?.role || "sin rol"} · ${developerState.actors.find(a=>a.id===id)?.family || "sin familia"}`; return ""; }
function applyDeveloperAdvancedJson() { try { const next = JSON.parse(document.getElementById("developerAdvancedJson").value); if (!next.id || !Array.isArray(next.options)) throw new Error("El evento debe tener id y options[]."); const current = selectedEvent(); developerState.events[developerState.events.indexOf(current)] = next; developerState.selected.events = next.id; developerState.jsonError = ""; renderDeveloperEditor(); } catch (err) { developerState.jsonError = err.message; renderDeveloperEditor(); } }
function formatDeveloperAdvancedJson() { try { const box = document.getElementById("developerAdvancedJson"); box.value = JSON.stringify(JSON.parse(box.value), null, 2); } catch (err) { developerState.jsonError = err.message; renderDeveloperEditor(); } }
function openDeveloperEvent(id) { if (!id) return; developerState.activeTab = "events"; developerState.selected.events = id; developerState.eventTab = "general"; renderDeveloperEditor(); }
function goDeveloperProblem(tab, id) { developerState.activeTab = tab || "events"; if (id && developerState.selected[developerState.activeTab] !== undefined) developerState.selected[developerState.activeTab] = id; renderDeveloperEditor(); }
function addEffect(field) { const event = selectedEvent(), [,iText]=field.split(":"), option=event.options[Number(iText)]; option.immediate = option.immediate || {}; option.immediate[[...RESOURCE_KEYS][0]] = 0; renderDeveloperEditor(); }
function deleteEffect(field,index) { const option=selectedEvent().options[Number(field.split(":")[1])], key=Object.keys(option.immediate || {})[index]; delete option.immediate[key]; renderDeveloperEditor(); }
function addCharacter(i) { const option=selectedEvent().options[i]; option.characters=[...(option.characters||[]),{id:developerState.actors[0]?.id || ""}]; renderDeveloperEditor(); }
function deleteCharacter(oi,ci) { selectedEvent().options[oi].characters.splice(ci,1); renderDeveloperEditor(); }
function addDefer(i) { const option=selectedEvent().options[i]; option.defer=[...optionList(option.defer),{ delay:1, eventId:"" }]; renderDeveloperEditor(); }
function deleteDefer(oi,di) { const option=selectedEvent().options[oi], list=optionList(option.defer); list.splice(di,1); option.defer=list; renderDeveloperEditor(); }
function exportDeveloperDatabase() { const blob = new Blob([JSON.stringify(buildDeveloperDatabase(), null, 2)], { type:"application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "su-majestad-database-export.json"; link.click(); URL.revokeObjectURL(link.href); }
function importDeveloperDatabase(e) { const file = e.target.files?.[0]; if (!file) return; file.text().then((text)=>{ const parsed=JSON.parse(text), db=Array.isArray(parsed)?{events:parsed}:parsed; if (!Array.isArray(db.events)) throw new Error("El JSON debe contener events[]."); developerState.events=db.events; if (Array.isArray(db.families)) developerState.families=db.families; if (Array.isArray(db.actors)) developerState.actors=db.actors; developerState.selected.events=developerState.events[0]?.id || null; renderDeveloperEditor("Base de datos importada en memoria."); }).catch((err)=>alert(`No se pudo importar: ${err.message}`)); e.target.value=""; }
function loadDeveloperDraft() { const text = localStorage.getItem(DEV_DATABASE_DRAFT_KEY); if (!text) return renderDeveloperEditor("No hay borrador guardado."); const db=JSON.parse(text); developerState.events=db.events || []; developerState.families=db.families || []; developerState.actors=db.actors || []; renderDeveloperEditor("Borrador cargado."); }
function validateDeveloperDatabase() { const errors=[], warnings=[], ids=new Set(), familyIds=new Set(developerState.families.map(f=>f.id)), actorIds=new Set(developerState.actors.map(a=>a.id)); const push=(arr,message,tab="events",recordId="")=>arr.push({message,tab,recordId}); developerState.events.forEach((e)=>{ if (!e.id) push(errors,"Evento sin ID","events",e.id); else if (ids.has(e.id)) push(errors,`ID duplicado: ${e.id}`,"events",e.id); ids.add(e.id); if (!e.title) push(errors,`${e.id}: falta título`,"events",e.id); if (!e.text) push(errors,`${e.id}: falta texto`,"events",e.id); if (!Array.isArray(e.options) || !e.options.length) push(errors,`${e.id}: no tiene opciones`,"events",e.id); if (e.family && !familyIds.has(e.family)) push(warnings,`${e.id}: familia inexistente ${e.family}`,"events",e.id); validateResourceMap(e.resourceConditions, `${e.id}: resourceConditions`, errors, e.id); (e.resourceWeights || []).forEach((r,i)=>validateResourceRule(r,`${e.id}: resourceWeights ${i+1}`,errors,e.id)); (e.options||[]).forEach((o,oi)=>validateOption(e,o,oi,ids,actorIds,errors,warnings)); }); developerState.actors.forEach(a=>{ if(a.family && !familyIds.has(a.family)) push(warnings,`${a.id}: actor con familia inexistente ${a.family}`,"actors",a.id); if(!eventsUsingActor(a.id).length) push(warnings,`${a.id}: actor sin uso`,"actors",a.id); }); developerState.families.forEach(f=>{ if(!eventsUsingFamily(f.id).length) push(warnings,`${f.id}: familia sin uso`,"families",f.id); }); tagIndex().filter(t=>t.count===1).forEach(t=>push(warnings,`${t.tag}: tag usado una sola vez`,"gameData","")); return { errors, warnings }; }
function validateOption(e,o,oi,ids,actorIds,errors,warnings) { const push=(arr,message)=>arr.push({message,tab:"events",recordId:e.id}); if(!o.label) push(errors,`${e.id}: opción ${oi+1} sin label`); [o.immediate,o.effects,...(o.outcomes||[]).map(x=>x.immediate||x.effects)].filter(Boolean).forEach(m=>validateResourceMap(m,`${e.id}: opción ${oi+1}`,errors,e.id)); (o.characters||[]).forEach(c=>{ if(c.id && !actorIds.has(c.id)) push(warnings,`${e.id}: actor inexistente ${c.id}`); }); (o.outcomes||[]).forEach((out)=>{ if(out.probability != null && (Number(out.probability)<0 || Number(out.probability)>1)) push(errors,`${e.id}: probability fuera de rango`); }); const sum=(o.outcomes||[]).reduce((a,x)=>a+(Number(x.probability)||0),0); if(o.outcomes?.length && Math.abs(sum-1)>0.05) push(warnings,`${e.id}: outcomes no suman aproximadamente 1`); optionList(o.defer).forEach((d)=>{ if(!Number.isFinite(Number(d.delay)) || Number(d.delay)<1) push(errors,`${e.id}: defer.delay debe ser >= 1`); if(d.eventId && !ids.has(d.eventId)) push(errors,`${e.id}: defer.eventId inexistente ${d.eventId}`); const branchSum=(d.branches||[]).reduce((a,b)=>a+(Number(b.probability)||0),0); if(d.branches?.length && Math.abs(branchSum-1)>0.05) push(warnings,`${e.id}: ramas defer no suman aproximadamente 1`); (d.branches||[]).forEach(b=>{ if(b.eventId && !ids.has(b.eventId)) push(errors,`${e.id}: rama defer inexistente ${b.eventId}`); }); }); }
function validateResourceMap(map,label,errors,recordId) { if(!map || typeof map!=="object") return; Object.keys(map).forEach(k=>{ if(!RESOURCE_KEYS.has(k)) errors.push({message:`${label}: recurso inválido ${k}`,tab:"events",recordId}); }); }
function validateResourceRule(rule,label,errors,recordId) { if(rule?.resource && !RESOURCE_KEYS.has(rule.resource)) errors.push({message:`${label}: recurso inválido ${rule.resource}`,tab:"events",recordId}); }
function tagIndex() { const map=new Map(), add=(tag,where)=>{ if(!tag) return; const item=map.get(tag)||{tag,count:0,where:[]}; item.count++; item.where.push(where); map.set(tag,item); }; developerState.events.forEach(e=>{ (e.requiresTags||[]).forEach(t=>add(t,e.id)); (e.forbiddenTags||[]).forEach(t=>add(t,e.id)); (e.options||[]).forEach(o=>(o.addTags||[]).forEach(t=>add(t,e.id))); }); developerState.families.forEach(f=>(f.commonTags||[]).forEach(t=>add(t,`familia:${f.id}`))); developerState.actors.forEach(a=>(a.tags||[]).forEach(t=>add(t,`actor:${a.id}`))); return [...map.values()].sort((a,b)=>b.count-a.count || a.tag.localeCompare(b.tag)); }
function issueTypeIndex() { const map=new Map(); developerState.events.forEach(e=>(e.options||[]).forEach(o=>(o.issues||[]).forEach(i=>{ const id=i.type||i.id||i.issue; if(!id) return; const item=map.get(id)||{id,events:[]}; item.events.push(e.id); map.set(id,item); }))); return [...map.values()]; }
function eventsUsingFamily(id) { return developerState.events.filter(e=>e.family===id); }
function eventsUsingActor(id) { return developerState.events.filter(e=>(e.options||[]).some(o=>(o.characters||[]).some(c=>c.id===id))); }
function eventHasDefer(e) { return (e.options||[]).some(o=>optionList(o.defer).length); }
function eventHasIssue(e) { return Boolean(e.issue || (e.options||[]).some(o=>o.issues?.length)); }
function summarizeOption(o) { const effects = Object.entries(o.immediate || {}).map(([k,v]) => `${resourceMeta[k]?.[0] || k} ${Number(v)>0?"↑":"↓"}`).join(" · "); const flags = [o.addTags?.length?"Tags":"", o.characters?.length?"Actores":"", optionList(o.defer).length?"Defer":"", o.outcomes?.length?"Outcomes":""].filter(Boolean).join(" · "); return [effects, flags].filter(Boolean).join(" · ") || "Sin efectos visibles"; }
function uniqueId(base, list) { const ids=new Set(list.map(x=>x.id)); let id=String(base).replace(/[^a-z0-9_]+/gi,"_").toLowerCase(), i=2; while(ids.has(id)) id=`${base}_${i++}`; return id; }
function csv(value) { return String(value || "").split(",").map((x)=>x.trim()).filter(Boolean); }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>"]/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" }[char])); }
bootDeveloperEditor();
