function event(id, title, text, options, extra = {}) {
  return { id, title, text, options: options.map(normalizeOption), ...extra };
}

function normalizeOption(option) {
  const [label, effectsOrConfig, config = {}] = option;
  if (effectsOrConfig && (effectsOrConfig.immediate || effectsOrConfig.effects || effectsOrConfig.outcomes || effectsOrConfig.defer || effectsOrConfig.addTags || effectsOrConfig.characters || effectsOrConfig.issues)) {
    return { label, immediate: {}, ...effectsOrConfig };
  }
  return { label, immediate: effectsOrConfig || {}, ...config };
}

const events = [
  event("rats_granary", "Granero con ratas", "Las reservas del norte han sido infestadas.", [["Quemad el granero", { food: -8, threat: -3, people: -2 }, { addTags: ["decisive_ruler"] }], ["Contratad cazadores", { gold: -6, food: -3, people: 2 }], ["Ignoradlo", { food: -10 }, { defer: [{ delay: 4, eventId: "rats_return" }] }]]),
  event("foreign_merchants", "Mercaderes extranjeros", "Una caravana de telas y especias espera audiencia. Su portavoz, Dario Valen, promete recordar la mano que le abra la puerta.", [["Cobrad impuestos", { gold: 8, people: -2 }, { addTags: ["taxed_merchants"], characters: [{ id: "dario", name: "Dario Valen", role: "mercader" }], defer: [{ delay: 6, branches: [{ probability: 0.45, eventId: "dario_smuggling" }, { probability: 0.35, eventId: "dario_pays_due" }, { probability: 0.20, eventId: "dario_leaves" }] }] }], ["Dadles escolta", { army: -2 }, { addTags: ["supported_merchants"], characters: [{ id: "dario", name: "Dario Valen", role: "mercader aliado" }], defer: [{ delay: 6, branches: [{ probability: 0.60, eventId: "dario_prospers" }, { probability: 0.30, eventId: "dario_robbed" }, { probability: 0.10, eventId: "dario_missing" }] }] }], ["Cerrad las puertas", { threat: -2 }, { addTags: ["closed_gates_to_merchants"] }]]),
  event("prophet_square", "Profeta en la plaza", "Un predicador arrastra multitudes y pregunta si la corona teme a la verdad.", [["Bendecidlo", { faith: 6 }, { addTags: ["helped_church"], defer: [{ delay: 5, eventId: "church_remembers" }] }], ["Arrestadlo", { faith: -6, people: -3, threat: -2 }, { addTags: ["angered_church"] }], ["Invitadlo a palacio", { gold: -3, faith: 3 }, { addTags: ["courted_church"] }]]),
  event("noble_duel", "Duelo noble", "Dos casas rivales exigen que arbitres su honor.", [["Favoreced al duque", { nobility: 4, people: -2 }, { addTags: ["favored_nobles"] }], ["Multad a ambos", { gold: 6, nobility: -5 }, { addTags: ["angered_nobles"] }], ["Ejecutad al instigador", { nobility: -8, threat: -4 }, { addTags: ["executed_noble", "angered_nobles"], defer: [{ delay: 7, eventId: "noble_blood_feud" }] }]]),
  event("road_bandits", "Bandidos del camino", "Los aldeanos temen viajar al mercado.", [["Patrulla militar", { army: -4, people: 4, threat: -5 }, { addTags: ["protected_roads"], defer: [{ delay: 5, branches: [{ probability: 0.65, eventId: "bandits_scattered" }, { probability: 0.35, eventId: "ambushed_patrol" }] }] }], ["Pagad informantes", { gold: -5, threat: -4 }, { addTags: ["spy_network"] }], ["Ejecutad capturados", { people: -2, threat: -6 }, { addTags: ["executed_bandits"] }]]),
  event("golden_harvest", "Cosecha dorada", "Los campos producen más de lo esperado.", [["Almacenar", { outcomes: [{ probability: 0.55, immediate: { food: 10 }, text: "El grano se conserva bien." }, { probability: 0.30, immediate: { food: 4 }, text: "Parte del grano se estropea." }, { probability: 0.15, immediate: { food: -5 }, text: "Una plaga arruina los almacenes." }] }], ["Celebrar feria", { food: 5, gold: 4, people: 3 }, { addTags: ["held_fair"] }], ["Diezmo especial", { food: 3, faith: 4, people: -2 }, { addTags: ["helped_church"] }]]),
  event("war_tax", "Impuesto de guerra", "Los cofres menguan y la frontera arde.", [["Cobrar al pueblo", { gold: 10, people: -6 }, { addTags: ["rejected_tax_mercy"] }], ["Cobrar a nobles", { gold: 8, nobility: -6 }, { addTags: ["angered_nobles"] }], ["Perdonar impuestos", {}, { addTags: ["rejected_taxes"], defer: [{ delay: 4, eventId: "tax_mercy_remembered" }] }]]),
  event("ancient_map", "Mapa antiguo", "Un cartógrafo vende rutas hacia ruinas olvidadas.", [["Financiad exploradores", { gold: -5, army: -2 }, { addTags: ["funded_explorers"], defer: [{ delay: 8, branches: [{ probability: 0.50, eventId: "explorers_relic" }, { probability: 0.30, eventId: "explorers_lost" }, { probability: 0.20, eventId: "explorers_warning" }] }] }], ["Subastad mapa", { gold: 6, nobility: 1 }], ["Entregad al templo", { faith: 4 }, { addTags: ["helped_church"] }]]),

  event("dario_prospers", "Regreso de {character:dario.name}", "{character:dario.name} vuelve con caravanas llenas. No habla de 'la corona', habla de ti.", [["Aceptad su regalo", { gold: 10, food: 4 }, { addTags: ["dario_grateful", "supported_merchants"] }], ["Pedid inversión pública", { people: 5 }, { addTags: ["merchant_public_works"] }]], { kind: "consequence", requiresTags: ["supported_merchants"] }),
  event("dario_robbed", "La caravana de {character:dario.name} fue asaltada", "El mercader sobrevivió, pero culpa a tus caminos y exige justicia.", [["Compensadlo", { gold: -6, people: 2 }, { addTags: ["dario_compensated"] }], ["Cazad a los culpables", { army: -3, threat: -5 }, { addTags: ["protected_roads"] }]], { kind: "consequence" }),
  event("dario_missing", "Silencio en la ruta", "Nadie ha visto a {character:dario.name}. Sus socios murmuran que comerciar contigo trae mala suerte.", [["Enviar búsqueda", { gold: -4, threat: -2 }, { addTags: ["searched_for_dario"] }], ["Negar responsabilidad", { people: -3 }, { addTags: ["abandoned_merchants"] }]], { kind: "consequence" }),
  event("dario_smuggling", "El viejo trato de {character:dario.name}", "Tras los impuestos, {character:dario.name} mueve mercancía por pasos secretos.", [["Amnistía por multa", { gold: 7 }, { addTags: ["merchant_amnesty"] }], ["Confiscarlo todo", { gold: 5, people: -3 }, { addTags: ["angered_merchants"] }]], { kind: "consequence", requiresTags: ["taxed_merchants"] }),
  event("dario_pays_due", "Tributo de {character:dario.name}", "El mercader pagó, prosperó y trae una bolsa sellada con tu escudo.", [["Aceptar tributo", { gold: 8 }], ["Reducir sus tasas futuras", {}, { addTags: ["supported_merchants"] }]], { kind: "consequence" }),
  event("dario_leaves", "Una ruta menos", "Los puestos de {character:dario.name} han cerrado. Otros mercaderes preguntan si serán los siguientes.", [["Prometer privilegios", { gold: -3 }, { addTags: ["supported_merchants"] }], ["Que aprendan obediencia", { nobility: 2, people: -2 }]], { kind: "consequence" }),
  event("church_remembers", "La iglesia devuelve el favor", "Los sacerdotes recuerdan tu apoyo y calman a los barrios inquietos.", [["Agradeced desde el balcón", { faith: 4, people: 3 }], ["Pedid donativos", { gold: 5, faith: -2 }]], { kind: "consequence", requiresTags: ["helped_church"] }),
  event("noble_blood_feud", "Sangre noble pide sangre", "La familia del ejecutado no olvida. Sus vasallos retrasan tributos y afilan juramentos.", [["Convocad juicio público", { gold: -3, nobility: -2, people: 3 }, { addTags: ["public_justice"] }], ["Aplastad la casa", { army: -5, nobility: -6, threat: -3 }, { addTags: ["crushed_noble_house"] }]], { kind: "consequence", requiresTags: ["executed_noble"] }),
  event("bandits_scattered", "Caminos abiertos", "Las patrullas vuelven con estandartes de bandidos. Los mercados respiran.", [["Premiad a la patrulla", { gold: -3, army: 3, people: 3 }], ["Exhibid los estandartes", { threat: -4 }]], { kind: "consequence" }),
  event("ambushed_patrol", "Emboscada en el bosque", "La patrulla enviada contra bandidos regresa diezmada.", [["Enviar refuerzos", { army: -5, threat: -4 }], ["Negociar con aldeanos", { gold: -4, people: 2 }]], { kind: "consequence" }),
  event("tax_mercy_remembered", "El perdón en los impuestos", "Los recaudadores informan que el pueblo cita tu perdón como prueba de que el trono escucha.", [["Mantener la promesa", { people: 5 }], ["Recuperar parte ahora", { gold: 5, people: -3 }]], { kind: "consequence", requiresTags: ["rejected_taxes"] }),
  event("explorers_relic", "Los exploradores regresan", "La expedición financiada trae una reliquia y mapas de pasos seguros.", [["Consagrar la reliquia", { faith: 5, threat: -3 }], ["Vender hallazgos", { gold: 9 }]], { kind: "consequence", requiresTags: ["funded_explorers"] }),
  event("explorers_lost", "No vuelven los exploradores", "Solo llega una mochila rasgada. Las familias piden respuestas.", [["Pensionar familias", { gold: -5, people: 4 }], ["Cerrar el expediente", { people: -4, nobility: 2 }]], { kind: "consequence", requiresTags: ["funded_explorers"] }),
  event("explorers_warning", "Advertencia desde las ruinas", "Tus exploradores hallaron columnas quemadas por un enemigo antiguo.", [["Fortificar pasos", { gold: -5, threat: -6 }], ["Ocultar el informe", { nobility: 2, threat: 3 }]], { kind: "consequence", requiresTags: ["funded_explorers"] }),

  event("border_refugees", "Refugiados en la frontera", "Familias de la marca oriental llegan con carros quemados. Traen noticias de una guerra que aún no aparece en tus mapas.", [["Abrid los graneros", { food: -7, people: 5 }, { issues: [{ action: "create", issue: { id: "border-crisis", actorId: "marca_oriental", type: "border", stage: 0, tension: 38, trust: 45, tags: ["refugees"] } }], defer: [{ delay: 5, eventId: "border_raiders" }] }], ["Interrogadlos primero", { threat: -2, people: -2 }, { issues: [{ action: "create", issue: { id: "border-crisis", actorId: "marca_oriental", type: "border", stage: 0, tension: 46, trust: 30, tags: ["suspected_spies"] } }] }], ["Cerrad la frontera", { threat: -4, people: -5 }, { addTags: ["closed_border"], defer: [{ delay: 4, eventId: "border_raiders" }] }]], { weight: 1.2, family: "border", families: ["border"] }),
  event("border_raiders", "Jinetes tras los refugiados", "Los perseguidores cruzan mojones reales y prueban tus torres. La marca oriental exige una respuesta que no parezca azar ni pánico.", [["Enviar caballería", { army: -5, threat: -6 }, { issues: [{ action: "modify", issueId: "border-crisis", tension: -12, trust: 10 }], defer: [{ delay: 6, eventId: "border_envoy" }] }], ["Pagar tributo fronterizo", { gold: -8, threat: -3, nobility: -2 }, { issues: [{ action: "modify", issueId: "border-crisis", tension: -8, trust: -3 }] }], ["Ignorar la incursión", { people: -4, threat: 7 }, { issues: [{ action: "escalate", issueId: "border-crisis", tension: 10, trust: -12 }], defer: [{ delay: 4, eventId: "border_burns" }] }]], { kind: "consequence", family: "border", issue: { id: "border-crisis", maxStage: 1 } }),
  event("border_burns", "La marca arde", "Tres aldeas fronterizas prenden hogueras de auxilio. El asunto ya no es una queja: es una herida abierta del reino.", [["Nombrar un mariscal", { gold: -4, army: -4, threat: -8 }, { issues: [{ action: "escalate", issueId: "border-crisis", tension: -5, trust: 8 }], defer: [{ delay: 5, eventId: "border_envoy" }] }], ["Ordenar leva local", { army: 5, people: -6, nobility: -3 }, { issues: [{ action: "escalate", issueId: "border-crisis", tension: 8, trust: -6 }] }]], { kind: "consequence", family: "border", issue: { id: "border-crisis" } }),
  event("border_envoy", "El enviado de la marca", "Un capitán cubierto de polvo pide fueros, soldados y una promesa sellada. Si lo atiendes, el problema puede convertirse en alianza.", [["Firmar los fueros", { gold: -6, nobility: -3, people: 5, threat: -6 }, { addTags: ["border_oath"], issues: [{ action: "resolve", issueId: "border-crisis", addTags: ["border_secured"] }] }], ["Exigir obediencia antes de ayuda", { nobility: 3, people: -3 }, { issues: [{ action: "escalate", issueId: "border-crisis", tension: 10, trust: -10 }], defer: [{ delay: 5, eventId: "border_last_stand" }] }]], { kind: "consequence", family: "border", issue: { id: "border-crisis" } }),
  event("border_last_stand", "Último estandarte oriental", "La marca oriental combate sola bajo tu blasón. La decisión de hoy escribirá si la frontera fue abandonada o integrada al reino.", [["Marchar personalmente", { army: -8, gold: -5, people: 4, threat: -12 }, { addTags: ["border_hero"], issues: [{ action: "resolve", issueId: "border-crisis", addTags: ["border_secured"] }] }], ["Conceder independencia de defensa", { nobility: -5, threat: -5 }, { addTags: ["border_autonomy"], issues: [{ action: "resolve", issueId: "border-crisis", addTags: ["border_autonomy"] }] }], ["Retirar el blasón", { army: 3, people: -10, threat: 12 }, { addTags: ["abandoned_border"], issues: [{ action: "resolve", issueId: "border-crisis" }] }]], { kind: "consequence", family: "border", issue: { id: "border-crisis", minStage: 1 } }),

  event("noble_petition", "Petición de una casa inquieta", "Una familia menor pide tierras disputadas. Es un asunto modular: puede morir aquí o crecer dos escalones.", [["Conceded las tierras", { nobility: 4, people: -3 }, { issues: [{ action: "create", issue: { id: "house-varela-claim", actorId: "house_varela", type: "noble_claim", stage: 0, tension: 30, trust: 55, tags: ["land_claim"] } }] }], ["Aplazar sentencia", { nobility: -2 }, { issues: [{ action: "create", issue: { id: "house-varela-claim", actorId: "house_varela", type: "noble_claim", stage: 0, tension: 42, trust: 40, tags: ["delayed_claim"] } }], defer: [{ delay: 5, eventId: "noble_claim_escalates" }] }], ["Rechazarla", { nobility: -5, people: 2 }, { issues: [{ action: "create", issue: { id: "house-varela-claim", actorId: "house_varela", type: "noble_claim", stage: 1, tension: 55, trust: 25, tags: ["insulted"] } }], defer: [{ delay: 4, eventId: "noble_claim_escalates" }] }]], { weight: 1, family: "noble_claim", families: ["noble_claim"] }),
  event("noble_claim_escalates", "La casa Varela sube el tono", "Sus sellos llegan rotos y sus hombres retrasan diezmos. La disputa sigue dentro de su arquetipo: tierras, honor y vasallaje.", [["Mediar con testigos", { gold: -4, nobility: 2, people: 2 }, { issues: [{ action: "modify", issueId: "house-varela-claim", tension: -20, trust: 12 }] }], ["Amenazar con confiscaciones", { threat: -3, nobility: -4 }, { issues: [{ action: "escalate", issueId: "house-varela-claim", tension: 8, trust: -8 }], defer: [{ delay: 5, eventId: "noble_claim_duel" }] }], ["Cerrar el caso", { nobility: -2 }, { issues: [{ action: "resolve", issueId: "house-varela-claim", addTags: ["varela_settled"] }] }]], { kind: "consequence", family: "noble_claim", issue: { id: "house-varela-claim", maxStage: 1 } }),
  event("noble_claim_duel", "Duelos por la heredad", "La segunda escalada llega con acero desnudo. Ya no hay combinaciones libres: es la culminación natural de una reclamación noble.", [["Reconocer un campeón real", { army: -2, nobility: 4, threat: -3 }, { issues: [{ action: "resolve", issueId: "house-varela-claim", addTags: ["varela_bound"] }] }], ["Prohibir los duelos", { nobility: -6, people: 3, threat: -2 }, { issues: [{ action: "resolve", issueId: "house-varela-claim", addTags: ["duels_banned"] }] }]], { kind: "consequence", family: "noble_claim", issue: { id: "house-varela-claim", minStage: 1 } })
];
